title: "San Diego Cyber Conference"
description: "An opportunity for undergrads to publish and present research, projects, and ideas."

url: "https://jackdeterman.github.io"
baseurl: "/CDS_Conference"

# Use Minimal Mistakes
remote_theme: "mmistakes/minimal-mistakes"

plugins:
  - jekyll-include-cache


header_pages:
- index.md
- submission.md
- schedule.md
- contact.md

atom_feed:
  hide: true

footer:
  links:
    - label: "Instagram"
      url: "https://www.instagram.com/sd_cyber_conf"
      icon: "fab fa-instagram"

# Theme settings
minimal_mistakes_skin: "sunrise"
include: ["assets/css/custom.css"]
